name := "functional programming in scala"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.0.1"
libraryDependencies += "org.scalatest" % "scalatest_2.11" % "3.0.1" % "test"
resolvers += "Artima Maven Repository" at "http://repo.artima.com/releases"
version := "1.0"
scalaVersion := "2.11.8"
